# Generated by Django 4.0.6 on 2022-08-19 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000)),
                ('agora', models.DateField(verbose_name=datetime.datetime(2022, 8, 19, 9, 16, 33, 205845))),
                ('texto', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='imagens/')),
            ],
        ),
    ]
